const avatars = [
  {position:1,avatar:require('./101.png')},
  {position:2,avatar:require('./2.png')},
  {position:3,avatar:require('./3.png')},
  {position:4,avatar:require('./4.png')},
  {position:5,avatar:require('./5.png')},
  {position:6,avatar:require('./6.png')},
  {position:7,avatar:require('./7.png')},
  {position:8,avatar:require('./8.png')},
  {position:9,avatar:require('./9.png')},
  {position:10,avatar:require('./10.png')},
  {position:11,avatar:require('./11.png')},
  {position:12,avatar:require('./12.png')},
  {position:13,avatar:require('./13.png')},
  {position:14,avatar:require('./14.png')},
  {position:15,avatar:require('./15.png')},
  {position:16,avatar:require('./16.png')},
  {position:17,avatar:require('./17.png')},
  {position:18,avatar:require('./18.png')},
  {position:19,avatar:require('./19.png')},
  {position:20,avatar:require('./20.png')},
  {position:21,avatar:require('./21.png')},
  {position:22,avatar:require('./22.png')},
  {position:23,avatar:require('./23.png')},
  {position:24,avatar:require('./24.png')},
  {position:25,avatar:require('./25.png')},
  {position:26,avatar:require('./26.png')},
  {position:27,avatar:require('./27.png')},
  {position:28,avatar:require('./28.png')},
  {position:29,avatar:require('./29.png')},
  {position:30,avatar:require('./30.png')},
  {position:31,avatar:require('./31.png')},
  {position:32,avatar:require('./32.png')},
  {position:33,avatar:require('./33.png')},
  {position:34,avatar:require('./34.png')},
  {position:35,avatar:require('./35.png')},
  {position:36,avatar:require('./36.png')},
  {position:37,avatar:require('./37.png')},
  {position:38,avatar:require('./38.png')},
  {position:39,avatar:require('./39.png')},
  {position:40,avatar:require('./40.png')},
  {position:41,avatar:require('./41.png')},
  {position:42,avatar:require('./42.png')},
  {position:43,avatar:require('./43.png')},
  {position:44,avatar:require('./44.png')},
  {position:45,avatar:require('./45.png')},
  {position:46,avatar:require('./46.png')},
  {position:47,avatar:require('./47.png')},
  {position:48,avatar:require('./48.png')},
  {position:49,avatar:require('./49.png')},
  {position:50,avatar:require('./50.png')},
  {position:51,avatar:require('./51.png')},
  {position:52,avatar:require('./52.png')},
  {position:53,avatar:require('./53.png')},
  {position:54,avatar:require('./54.png')},
  {position:55,avatar:require('./55.png')},
  {position:56,avatar:require('./56.png')},
  {position:57,avatar:require('./57.png')},
  {position:58,avatar:require('./58.png')},
  {position:59,avatar:require('./59.png')},
  {position:60,avatar:require('./60.png')},
  {position:61,avatar:require('./61.png')},
  {position:62,avatar:require('./62.png')},
  {position:63,avatar:require('./63.png')},
  {position:64,avatar:require('./64.png')},
  {position:65,avatar:require('./65.png')},
  {position:66,avatar:require('./66.png')},
  {position:67,avatar:require('./67.png')},
  {position:68,avatar:require('./68.png')},
  {position:69,avatar:require('./69.png')},
  {position:70,avatar:require('./70.png')},
  {position:71,avatar:require('./71.png')},
  {position:72,avatar:require('./72.png')},
  {position:73,avatar:require('./73.png')},
  {position:74,avatar:require('./74.png')},
  {position:75,avatar:require('./75.png')},
  {position:76,avatar:require('./76.png')},
  {position:77,avatar:require('./77.png')},
  {position:78,avatar:require('./78.png')},
  {position:79,avatar:require('./79.png')},
  {position:80,avatar:require('./80.png')},
  {position:81,avatar:require('./81.png')},
  {position:82,avatar:require('./82.png')},
  {position:83,avatar:require('./83.png')},
  {position:84,avatar:require('./84.png')},
  {position:85,avatar:require('./85.png')},
  {position:86,avatar:require('./86.png')},
  {position:87,avatar:require('./87.png')},
  {position:88,avatar:require('./88.png')},
  {position:89,avatar:require('./89.png')},
  {position:90,avatar:require('./90.png')},
  {position:91,avatar:require('./91.png')},
  {position:92,avatar:require('./92.png')},
  {position:93,avatar:require('./93.png')},
  {position:94,avatar:require('./94.png')},
  {position:95,avatar:require('./95.png')},
  {position:96,avatar:require('./96.png')},
  {position:97,avatar:require('./97.png')},
  {position:98,avatar:require('./98.png')},
  {position:99,avatar:require('./99.png')},
  {position:100,avatar:require('./100.png')},
];

const defaultAvatars = avatars.concat();

for (let i = 0; i < avatars.length; i++) {
  const random = Math.floor(Math.random() * (i + 1));
  [avatars[i], avatars[random]] = [avatars[random], avatars[i]];
}

export default avatars;
export {defaultAvatars}

