# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Askcoin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Askcoin

  pod 'AFNetworking', '~> 2.0'
  pod 'Masonry'

  pod 'React', :path => './../react_native/node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTNetwork',
    'RCTSettings',
    'RCTVibration',
    'RCTWebSocket',
  ]

  target 'AskcoinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AskcoinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
